# `name` value will appear "as is" in the badge.
# See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
# yamllint --format github .github/workflows/commit.yaml
---
name: "build"

on:
  push:  # We run tests on non-tagged pushes to main
    tags: ''
    branches: main
    paths-ignore:
      - '**/*.md'
  pull_request:  # We also run tests on pull requests targeted at the main branch.
    branches: main
    paths-ignore:
      - '**/*.md'
  # workflow_dispatch will let us manually trigger the workflow from GitHub actions dashboard.
  # For example, you can try to build a branch without raising a pull request.
  # See https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

env:
  WITX_CLI_VERSION: 0.9.1

jobs:
  check:
    name: Pre-commit check
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      # No precompiled binaries for witx so we build from crate
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-witx-${{ env.WITX_CLI_VERSION }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version ${{ env.WITX_CLI_VERSION }} witx-cli

      - name: Generate markdown
        run: witx docs -o http-host.md witx/http-host.witx

      - name: Check no diffs from generation
        run: test -z "$(git status --porcelain)" || (echo "Uncommited files detected, regenerate and commit docs." && exit 1)
